# Generated by Django 4.2.16 on 2024-11-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('difficulty', models.TextField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')])),
            ],
        ),
    ]
