# Generated by Django 4.2.16 on 2024-11-13 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_flashcardset'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='flashcard_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard', to='flashcard.flashcardset'),
            preserve_default=False,
        ),
    ]
