# Generated by Django 4.2.16 on 2024-11-13 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcard', '0003_flashcard_flashcard_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
