# Generated by Django 4.2.16 on 2024-11-13 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_flashcardcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardset',
            name='flashcard_collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_set', to='flashcard.flashcardcollection'),
            preserve_default=False,
        ),
    ]
