# Generated by Django 4.2.16 on 2024-11-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_flashcardset_flashcard_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardcollection',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
