# Generated by Django 4.2.16 on 2024-11-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0006_flashcardcollection_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardcollection',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flashcardset',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
