# Generated by Django 4.2.16 on 2024-11-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0007_alter_flashcardcollection_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardcollection',
            name='visibile',
            field=models.BooleanField(default=False),
        ),
    ]
