# Generated by Django 4.2.16 on 2024-11-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
